[package]
name = "renderling-example-blinn-phong"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
bytemuck = { version = "1.7.3", features = ["derive"] }
icosahedron = "^0.1"
nalgebra = "^0.30"
renderling = { path = "../../renderling", features = ["forward"] }
smol = "^1.2"
tracing = "^0.1"
tracing-log = "0.1.2"
tracing-subscriber = "^0.3"
winit = "^0.26"
wgpu = "^0.12"
