#![allow(dead_code)]
//! Automatically generated by Renderling's `build.rs`.
use crate::linkage::ShaderLinkage;
#[cfg(not(target_arch = "wasm32"))]
mod target {
    pub const ENTRY_POINT: &str = "convolution::shader::prefilter_environment_cubemap_vertex";
    pub fn descriptor() -> wgpu::ShaderModuleDescriptor<'static> {
        wgpu::include_spirv!(
            "../../shaders/convolution-shader-prefilter_environment_cubemap_vertex.spv"
        )
    }
    pub fn linkage(device: &wgpu::Device) -> super::ShaderLinkage {
        log::debug!(
            "creating native linkage for {}",
            "prefilter_environment_cubemap_vertex"
        );
        super::ShaderLinkage {
            entry_point: ENTRY_POINT,
            module: device.create_shader_module(descriptor()).into(),
        }
    }
}
#[cfg(target_arch = "wasm32")]
mod target {
    pub const ENTRY_POINT: &str = "convolutionshaderprefilter_environment_cubemap_vertex";
    pub fn descriptor() -> wgpu::ShaderModuleDescriptor<'static> {
        wgpu::include_wgsl!(
            "../../shaders/convolution-shader-prefilter_environment_cubemap_vertex.wgsl"
        )
    }
    pub fn linkage(device: &wgpu::Device) -> super::ShaderLinkage {
        log::debug!(
            "creating web linkage for {}",
            "prefilter_environment_cubemap_vertex"
        );
        super::ShaderLinkage {
            entry_point: ENTRY_POINT,
            module: device.create_shader_module(descriptor()).into(),
        }
    }
}
pub fn linkage(device: &wgpu::Device) -> ShaderLinkage {
    target::linkage(device)
}
