[package]
name = "renderling_ui"
version = "0.3.0"
edition = "2021"
description = "User-friendly real-time 2d rendering. 🍖"
repository = "https://github.com/schell/renderling"
license = "MIT OR Apache-2.0"
keywords = ["game", "graphics", "shader", "rendering"]
categories = ["rendering", "game-development", "graphics"]
readme = "README.md"

[dependencies]
crabslab = {workspace = true}
bytemuck = {workspace = true}
glyph_brush = "0.7.8"
image = {workspace=true}
log = {workspace=true}
lyon = "1.0.1"
renderling = {version = "0.4.5", path = "../renderling"}
rustc-hash = {workspace = true}
wgpu = {workspace = true}

[dev-dependencies]
ctor = {workspace = true}
env_logger = {workspace = true}
img-diff = {path = "../img-diff"}
itertools = "0.13"
