[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "^0.24" }
renderling = { path = "../renderling" }
wgpu = "^0.16"
winit = "^0.27"