//! `wgpu` shaders
//! This module holds the various SPIR-V shaders used for rendering, and the `wgpu` code that instantiates their pipelines.
//! The .spv files are generated by a program in the main renderling repo.
//!
//! To run, from the repo's project directory use:
//! `cd shaders && cargo run --release`
//!
//! To add a new shader:
//! * add a new shader crate to shaders/ with your rust-gpu code
//! * add the shader crate name to the SHADERS const in shaders/build.rs
//! * add a tuple of the stem name of the spv file and the shader source (via env var - don't worry, you'll see)
//!   to the SHADERS const in shaders/src/main.rs
//! * run `cd shaders && cargo run --release`
#[cfg(feature = "ui")]
pub mod ui;

#[cfg(feature = "forward")]
pub mod forward {
    //! Forward shader `wgpu` types and operations.
    pub use renderling_forward::*;
}
