[package]
name = "shader-crate"
version = "0.1.0"
authors = ["Schell Carl Scivally <efsubenovex@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["game", "graphics", "shader", "rendering"]
categories = ["rendering", "game-development", "graphics"]
description = "Shaders for the renderling project"

[lib]
crate-type = ["dylib"]

[dependencies]
renderling-shader = { path = "../../crates/renderling-shader" }
spirv-std = "^0.8"
glam = { version = "0.24.1", default-features = false, features = ["libm"]}
